name: ddclient-snap
base: core20 
version: 'v3.9.1'
summary: "Update dynamic DNS entries for accounts on dynamic DNS services."
description: |
  Dynamic DNS services currently supported include:

  # DynDNS.com  - See http://www.dyndns.com for details on obtaining a free account.
  # Zoneedit    - See http://www.zoneedit.com for details.
  # EasyDNS     - See http://www.easydns.com for details.
  # NameCheap   - See http://www.namecheap.com for details
  # DslReports  - See http://www.dslreports.com for details
  # Sitelutions - See http://www.sitelutions.com for details
  # Loopia      - See http://www.loopia.se for details
  # Noip        - See http://www.noip.com/ for details
  # Freedns     - See http://freedns.afraid.org/ for details
  # ChangeIP    - See http://www.changeip.com/ for details
  # nsupdate    - See nsupdate(1) and ddns-confgen(8) for details
  # CloudFlare  - See https://www.cloudflare.com/ for details
  # Google      - See http://www.google.com/domains for details
  # Duckdns     - See https://duckdns.org/ for details
  # Freemyip    - See https://freemyip.com for details
  # woima.fi    - See https://woima.fi/ for details
  # Yandex      - See https://domain.yandex.com/ for details
  # DNS Made Easy - See https://dnsmadeeasy.com/ for details
  # DonDominio  - See https://www.dondominio.com for details
  # NearlyFreeSpeech.net - See https://www.nearlyfreespeech.net/services/dns for details
  # OVH         - See https://www.ovh.com for details
  # ClouDNS     - See https://www.cloudns.net
  # dinahosting - See https://dinahosting.com
  # Gandi       - See https://gandi.net

  DDclient now supports many of cable/dsl broadband routers.

  Comments, suggestions and requests: use the issues on https://github.com/ddclient/ddclient/issues/new

  The code was originally written by Paul Burry and is now hosted and maintained through github.com. Please check out http://ddclient.net
grade: stable
confinement: strict

apps:
  daemon:
    environment:
      LC_ALL: "C.UTF-8"
      PERL5LIB:  "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl-base/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.30/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.30.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30.0/"
      LD_LIBRARY_PATH: "$SNAP/usr/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/:$LD_LIBRARY_PATH"
    command: bin/ddclient --daemon 300 -foreground
    daemon: simple
    plugs:
      - network
  exec:
    environment:
      LC_ALL: "C.UTF-8"
      PERL5LIB:  "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl-base/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.30/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.30.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30.0/"
      LD_LIBRARY_PATH: "$SNAP/usr/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/:$LD_LIBRARY_PATH"
    command: bin/ddclient
    plugs:
      - network

layout:
  /etc/ddclient/ddclient.conf:
    bind-file: $SNAP_DATA/etc/ddclient/ddclient.conf
  /var/cache/ddclient/ddclient.cache:
    bind-file: $SNAP_DATA/var/cache/ddclient/ddclient.cache

parts:
  ddclient:
    plugin: dump
    source: https://github.com/ddclient/ddclient.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    stage-packages:
      - libdata-validate-ip-perl
      - libio-socket-inet6-perl
      - libio-socket-ssl-perl
      - libjson-pp-perl
      - libsys-hostname-long-perl
      - perl
      - perl-base
      - perl-modules
    organize:
      ddclient: bin/ddclient
    stage:
      - bin/ddclient
      - usr/bin
      - usr/lib
      - usr/share
      - etc/perl
