name: ddclient-snap
base: core20 
version: 'v3.9.1'
summary: "Update dynamic DNS entries for accounts on dynamic DNS services."
description: |
  Dynamic DNS services currently supported include: 
    - [services](https://github.com/ddclient/ddclient?tab=readme-ov-file#supported-services)
  Comments, suggestions and requests: use the issues on https://github.com/ddclient/ddclient/issues/new
  The code was originally written by Paul Burry and is now hosted and maintained through github.com.
  Please check out http://ddclient.net
grade: stable
confinement: strict

apps:
  ddclient-snap:
    environment:
      LC_ALL: "C.UTF-8"
      PERL5LIB:  "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl-base/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.30/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.30.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30.0/"
      LD_LIBRARY_PATH: "$SNAP/usr/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/:$LD_LIBRARY_PATH"
    command: bin/ddclient --daemon 300 -foreground
    daemon: simple
    plugs:
      - network
  exec:
    environment:
      LC_ALL: "C.UTF-8"
      PERL5LIB:  "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl-base/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.30/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.30.0/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.30.0/"
      LD_LIBRARY_PATH: "$SNAP/usr/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/:$LD_LIBRARY_PATH"
    command: bin/ddclient
    plugs:
      - network

layout:
  /etc/ddclient/ddclient.conf:
    bind-file: $SNAP_DATA/ddclient.conf
  /var/cache/ddclient/ddclient.cache:
    bind-file: $SNAP_COMMON/ddclient.cache

parts:
  ddclient:
    plugin: dump
    source: https://github.com/ddclient/ddclient.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    stage-packages:
      - libdata-validate-ip-perl
      - libio-socket-inet6-perl
      - libio-socket-ssl-perl
      - libjson-pp-perl
      - libsys-hostname-long-perl
      - perl
      - perl-base
      - perl-modules
    organize:
      ddclient: bin/ddclient
    stage:
      - bin/ddclient
      - usr/bin
      - usr/lib
      - usr/share
      - etc/perl
